In [1]:
import torch

In [2]:
t1= torch.tensor(4.) 

In [4]:
t2= torch.tensor([1., 2,3,4])
t2

tensor([1., 2., 3., 4.])

In [5]:
t3= torch.tensor([[1,2,3],[1,4,2]])
t3

tensor([[1, 2, 3],
        [1, 4, 2]])

In [9]:
x=torch.tensor(3.)
y=torch.tensor(4.,requires_grad=True)
z=torch.tensor(5.)

a=x*y+z
a

tensor(17., grad_fn=<AddBackward0>)

In [ ]:
a.backward()

as expected dy/dx has the same as x i.e., 3, and dy/dx has the value 1. Note that x.grad is None , because x doesn't have requires _grad setr to True. 

In [10]:
import numpy as np

x= np.array([[1,2],[3,4]])
x

array([[1, 2],
       [3, 4]])

In [12]:
y = torch.from_numpy(x)
y

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

In [13]:
x.dtype, y.dtype

(dtype('int32'), torch.int32)

In [16]:
torch.__version__

'1.10.2+cpu'

In [17]:
from torch.utils.data import TensorDataset

In [ ]:
train_ds = TensorDataset(input)

In [31]:
import numpy as np
a=np.arange(15,dtype="complex").reshape(3,5)
a.ndim
a.itemsize
a
# a.dtype

array([[ 0.+0.j,  1.+0.j,  2.+0.j,  3.+0.j,  4.+0.j],
       [ 5.+0.j,  6.+0.j,  7.+0.j,  8.+0.j,  9.+0.j],
       [10.+0.j, 11.+0.j, 12.+0.j, 13.+0.j, 14.+0.j]])

In [36]:
a=np.zeros((3,5))
a=np.empty((3,5))
a=np.arange(3,10,3)
a

array([3, 6, 9])

genrerating random number

In [73]:
a= np.random.random((4,6))
b= np.random.random((6,6))
# c=a-b
# print(a)
# print(b)
# print(c)
c=a@b
c

array([[0.80849749, 0.83219298, 1.24174032, 1.82020072, 0.79425639,
        1.38704351],
       [1.21838835, 1.21683765, 1.33596807, 2.18464134, 1.35346012,
        1.80384001],
       [1.06001241, 1.15715829, 1.15758445, 2.0033198 , 1.22315173,
        1.49743767],
       [0.96986023, 1.39386605, 1.41031467, 2.34887138, 1.00371993,
        1.46583142]])

In [102]:
d=np.random.randint(10,size=(7,7))
d

array([[5, 2, 0, 5, 4, 6, 5],
       [3, 6, 5, 8, 2, 3, 2],
       [9, 5, 6, 6, 7, 0, 6],
       [0, 0, 5, 5, 1, 5, 0],
       [7, 5, 9, 1, 9, 0, 5],
       [3, 6, 1, 3, 0, 1, 1],
       [0, 3, 3, 8, 3, 0, 2]])

In [105]:
d[-1:,-1:0]


array([], shape=(0, 0), dtype=int32)