In [1]:
import torch

In [2]:
t1= torch.tensor(4.) 

In [4]:
t2= torch.tensor([1., 2,3,4])
t2

tensor([1., 2., 3., 4.])

In [5]:
t3= torch.tensor([[1,2,3],[1,4,2]])
t3

tensor([[1, 2, 3],
        [1, 4, 2]])

In [9]:
x=torch.tensor(3.)
y=torch.tensor(4.,requires_grad=True)
z=torch.tensor(5.)

a=x*y+z
a

tensor(17., grad_fn=<AddBackward0>)

In [ ]:
a.backward()

as expected dy/dx has the same as x i.e., 3, and dy/dx has the value 1. Note that x.grad is None , because x doesn't have requires _grad setr to True. 

In [10]:
import numpy as np

x= np.array([[1,2],[3,4]])
x

array([[1, 2],
       [3, 4]])

In [12]:
y = torch.from_numpy(x)
y

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

In [13]:
x.dtype, y.dtype

(dtype('int32'), torch.int32)

In [14]:
print(torch.__version__)

1.10.2+cpu
